### ISSUE TITLE
Missing environment variable in configuration for `port`

### ISSUE THREAD

**Issue by bdeanindy** [grokify/smsbot-ringcentral-lita#4]
Received this error while trying to start the application following the current documentation. Need to add a `port` environment variable in the .env file and the app.json (for Heroku one-button, unless you plan on accepting the default in Heroku, in which case you do not need to add this in app.json).

```
benjamin.dean@LMRC3973:~/MyApps/bdean-smsbot-ringcentral-lita (HEAD: ref: refs/heads/master) $ lita
[2016-09-03 01:15:58 UTC] FATAL: Configuration type error: "port" must be one of: Integer, String.
[2016-09-03 01:15:58 UTC] FATAL: Lita configuration file could not be processed. The exception was:
exit
Full backtrace:
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:190:in `abort'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:190:in `check_types'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:165:in `call'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:165:in `block (2 levels) in build_leaf'
/Users/benjamin.dean/MyApps/bdean-smsbot-ringcentral-lita/lita_config.rb:9:in `block in <top (required)>'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/registry.rb:17:in `configure'
/Users/benjamin.dean/MyApps/bdean-smsbot-ringcentral-lita/lita_config.rb:3:in `<top (required)>'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:49:in `load'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/configuration_builder.rb:49:in `load_user_config'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita.rb:75:in `run'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/lib/lita/cli.rb:77:in `start'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/bin/lita:23:in `load'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/bin/lita:23:in `<main>'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/benjamin.dean/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by grokify** [comment]
The port for Heroku is set by the `PORT` environment variable.

However, to have this used you need to set the following environment variable `SMSBOT_HEROKU=true` shown in `lita_config.rb`.

`SMSBOT_HEROKU` should be mentioned in the docs.

**Comment by bdeanindy** [comment]
Odd, because once I defined `PORT` in the `.env` file and set it to 3000, this issue was no-more.

Is there something else I might be missing?

**Comment by grokify** [comment]
Merged
